version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3977:3977
    environment:
      DB_HOST: db
      DB_USER: 'root'
      DB_PASSWORD: 'next*'
      PORT: '3977'
      DB_PORT: '3306'
      DIALECT: 'mysql'
      DATABASE: 'atm_banco_next'
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: atm_banco_next
      MYSQL_USER: user_next
      MYSQL_ROOT_PASSWORD: next*
      MYSQL_PASSWORD: next*
